--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: nginx-app
  name: nginx-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nginx-app
  template: 
    metadata: 
      labels: 
        app: nginx-app
    spec: 
      containers: 
        - 
          image: "nginx:latest"
          name: nginx-container
          ports: 
            - 
              containerPort: 80
