apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-app
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        -
          image: "shubh4527/node-app:node-test-app"
          name: node-container
          ports:
            -
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
  - port: 9005
    targetPort: 3000
    nodePort: 30005
